sqoop import -Dmapreduce.job.user.classpath.first=true -Dmapreduce.map.maxattempts=20
--connect {$sqoop_naumen_jdbc}
--username {$sqoop_naumen_user}
--password {$sqoop_naumen_password}
--target-dir {$file_path}
--append
--num-mappers 1
--query "SELECT
id,
TO_CHAR(creation_date, 'yyyy-MM-dd HH24:MI:SS.US') as creation_date,
TO_CHAR(last_modified_date, 'yyyy-MM-dd HH24:MI:SS.US') as last_modified_date,
TO_CHAR(removal_date, 'yyyy-MM-dd HH24:MI:SS.US') as removal_date,
removed,
author_id,
case_id,
ci,
client_email,
client_name,
clientou_id,
TO_CHAR(datedecision, 'yyyy-MM-dd HH24:MI:SS.US') as datedecision,
deadLineDate_d,
TO_CHAR(deadlinetime, 'yyyy-MM-dd HH24:MI:SS.US') as deadlinetime,
descriptioninrtf,
facttime,
impact_id,
linkedsc,
location,
TO_CHAR(manualclosdate, 'yyyy-MM-dd HH24:MI:SS.US') as manualclosdate,
mark,
numreclass,
numref,
priority_id,
proccodeclose,
TO_CHAR(registration_date, 'yyyy-MM-dd HH24:MI:SS.US') as registration_date,
resolutiontime,
responsibleemployee_id,
responsibleteam_id,
resumptionsum, route,
servicetime_id,
sevicecomp,
slastop,
slmservice,
solution,
solvedbyemployee_id,
solvedbyteam_id,
state,
TO_CHAR(statestarttime, 'yyyy-MM-dd HH24:MI:SS.US') as statestarttime,
stdonechildsc,
techdesc,
TO_CHAR(timeclosing24, 'yyyy-MM-dd HH24:MI:SS.US') as timeclosing24,
timezone_id,
title,
urgency_id,
usercalls\$reaction1line_l as usercalls_reaction1line_l,
usercalls\$reaction2line_l as usercalls_reaction2line_l,
usercalls\$reaction3line_l as usercalls_reaction3line_l,
usercalls\$reaction4line_l as usercalls_reaction4line_l,
usercalls\$timetorectific_l as usercalls_timetorectific_l,
usercalls\$timework1line_l as usercalls_timework1line_l,
usercalls\$timework2line_l as usercalls_timework2line_l,
usercalls\$timework3line_l as usercalls_timework3line_l,
usercalls\$timework4line_l as usercalls_timework4line_l,
username,
wayaddressing,
whoclose,
whodocontr_em,
overduestate_s,
overduestate_d
FROM tbl_servicecall WHERE (id % {$sqoop_page_count} = {$sqoop_current_page}) and \$CONDITIONS"
--as-avrodatafile